include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    
    #custom rule
    avoid_catches_without_on_clauses: ignore
    omit_local_variable_types: ignore
    library_prefixes: ignore
    dead_code: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_types_on_closure_parameters: ignore
   

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true